version: "3.7"
services:
  web:
    build:
      context: ./django
    environment:
      - DEPLOYMENT=api
      - LC_CTYPE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - LOCAL_HOST=${LOCAL_HOST}
      - DJANGO_SUPERUSER_USERNAME={$DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DEBUG=${DEBUG}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - image_server_flask
    command:
      - /bin/sh
      - -c
      - |
        cd src/
        python manage.py runserver

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"

  image_server_flask:
    build:
      context: ./image_server_flask
    ports:
      - "8080:8080"
    volumes:
      - ./image_server_flask:/app
    environment:
      - LOCAL_HOST=${LOCAL_HOST}
      - DEBUG=${DEBUG}
    restart: unless-stopped

