version: "3.7"
services:
  web:
    build:
      context: ./django
    environment:
      - DEPLOYMENT=api
      - LC_CTYPE=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - DEBUG=True
    volumes:
      - ./django:/code
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - minio
    stdin_open: true
    tty: true
    env_file: .env
    restart: unless-stopped
    command: python3 /code/src/manage.py runserver 0.0.0.0:8000

  postgres:
    image: postgres:alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio_storage:/data
    command: server --console-address ":9001" /data

  ui:
    build: ./ui
    depends_on:
      - web
      - postgres
      - minio
    ports:
      - "3000:3000"

volumes:
  pgdata:
  minio_storage:

