version: "3.7"
services:
  web:
    build:
      context: ./django
    expose:
      - "8000"
    depends_on:
      - postgres
      - image_server_flask
    env_file: .env.prod
    command:
      - /bin/sh
      - -c
      - |
        cd src/
        gunicorn --bind 0.0.0.0:8000 tdsp.wsgi

  postgres:
    image: postgres:alpine
    env_file: .env.prod
    volumes:
      - pgdata:/var/lib/postgresql/data/
    expose:
      - "5432"

  image_server_flask:
    build:
      context: ./image_server_flask
    expose:
      - "8080"
    volumes:
      - ./image_server_flask:/app
    env_file: .env.prod
    restart: unless-stopped

  ui:
    build: ./ui
    depends_on:
      - web
      - postgres
      - image_server_flask
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/ui

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - web
      - image_server_flask
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata:
  image_server_flask:

networks:
  default:
    name: prod_net