version: "3.7"
services:
  web:
    build:
      context: ./django
    expose:
      - "8000"
    depends_on:
      - postgres
      - image_server_flask
    env_file: .env.prod
    volumes:
      - static_files:/code/src/django-static/

  postgres:
    image: postgres:alpine
    env_file: .env.prod
    volumes:
      - pg_prod_data:/var/lib/postgresql/data/
    expose:
      - "5432"

  image_server_flask:
    build:
      context: ./image_server_flask
    expose:
      - "8080"
    volumes:
      - ./image_server_flask:/app
    env_file: .env.prod
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.prod
    depends_on:
      - web
      - postgres
      - image_server_flask
    volumes:
      - ui_html:/usr/share/nginx/html/

  prometheus:
    image: prom/prometheus:v2.14.0
    volumes:
      - prometheus_data_prod:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    expose:
      - "9090"
  grafana:
    image: grafana/grafana
    env_file: .env.prod
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3060:3060"
    depends_on:
      - prometheus
      - postgres
      - web

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - image_server_flask
      - ui
    volumes:
      - static_files:/usr/share/nginx/django-static
      - ui_html:/usr/share/nginx/html
    env_file: .env.prod

volumes:
  pg_prod_data:
  prometheus_data_prod: { }
  image_server_flask:
  static_files:
  ui_html:

networks:
  default:
    name: prod_net