{
 "title": "Django Prometheus",
 "description": "Django metrics dashboard using korfuri/django-prometheus Prometheus metrics exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(django_db_new_connections_total, namespace)"
    }
   },
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(django_db_new_connections_total{namespace=~\"$namespace\"}, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Spendings and Revenue",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  cm.name AS \"creative_name\",\n  SUM(\n    CASE\n      WHEN n.win = TRUE THEN cfg.impression_revenue\n      ELSE 0\n    END\n    +\n    CASE\n      WHEN n.click = TRUE THEN cfg.click_revenue\n      ELSE 0\n    END\n    +\n    CASE\n      WHEN n.conversion = TRUE THEN cfg.conversion_revenue\n      ELSE 0\n    END\n  ) AS \"total_revenue\",\n  SUM(\n    CASE\n      WHEN n.win = TRUE THEN n.price\n      ELSE 0\n    END\n  ) AS \"total_spend\"\nFROM dsp_notificationmodel n\nJOIN dsp_bidresponsemodel br ON n.bid_response_id = br.id\nJOIN dsp_creativemodel cm ON br.external_id = cm.external_id\nJOIN dsp_bidrequestmodel breq ON n.bid_request_id = breq.id\nJOIN dsp_configmodel cfg ON breq.config_id = cfg.id\nWHERE cfg.current = TRUE\nGROUP BY cm.name\nORDER BY total_revenue DESC;\n"
    }
   ]
  },
  {
   "title": "Bid price",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  breq.timestamp AS \"time\",\n  cm.name AS \"creative_name\",\n  br.price AS \"price\"\nFROM dsp_bidresponsemodel br\nJOIN dsp_creativemodel cm ON br.external_id = cm.external_id\nJOIN dsp_bidrequestmodel breq ON br.bid_request_id = breq.id\nORDER BY breq.timestamp, cm.name;\n"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Win and Loss count by creative",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  cm.name AS creative_name,\n  COUNT(CASE WHEN n.win = TRUE THEN 1 END) AS win_count,\n  COUNT(CASE WHEN n.win = FALSE THEN 1 END) AS loss_count\nFROM dsp_bidresponsemodel br\nJOIN dsp_creativemodel cm ON br.external_id = cm.external_id\nJOIN dsp_notificationmodel n ON br.id = n.bid_response_id\nGROUP BY cm.name\nORDER BY win_count DESC, loss_count DESC;\n"
    }
   ]
  },
  {
   "title": "AVG price for creative",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT cm.name AS creative_name, AVG(br.price) AS avg_price\nFROM dsp_bidresponsemodel br\nJOIN dsp_creativemodel cm ON br.external_id = cm.external_id\nGROUP BY cm.name\nORDER BY avg_price DESC;"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "description": "increase(v range-vector) calculates the increase in the time series in the range vector. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for. The increase is extrapolated to cover the full time range as specified in the range vector selector, so that it is possible to get a non-integer result even if a counter increases only by integer increments.",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"4.+\",namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"5.+\",namespace=~\"$namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_view_transport_method_total{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[1m])) by(method, view)",
     "legendFormat": "{{method}} /{{view}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{namespace=~\"$namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|healthcheck\"}[5m])) by (job, le))",
     "legendFormat": "quantile=99.9"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_before_middlewares_total{namespace=~\"$namespace\", app=~\"^$app$\", view!~\"prometheus-django-metrics|healthcheck\"}[1m])) by(job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{namespace=~\"$namespace\", app=~\"^$app$\", view!~\"prometheus-django-metrics|healthcheck\"}[1m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Database Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_db_execute_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (vendor)",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  {
   "title": "Models stats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_model_deletes_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (model)",
     "legendFormat": "[{{model}}] deletes"
    },
    {
     "expr": "sum(irate(django_model_inserts_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (model)",
     "legendFormat": "[{{model}}] inserts"
    },
    {
     "expr": "sum(irate(django_model_updates_total{namespace=~\"$namespace\", app=~\"^$app$\"}[1m])) by (model)",
     "legendFormat": "[{{model}}] updates"
    }
   ]
  }
 ]
}