# Generated by Django 4.1.7 on 2023-03-31 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BidRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(max_length=255, unique=True)),
                ('banner_width', models.IntegerField()),
                ('banner_height', models.IntegerField()),
                ('click_probability', models.FloatField()),
                ('conversion_probability', models.FloatField()),
                ('site_domain', models.CharField(max_length=255)),
                ('ssp_id', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BidResponseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField()),
                ('bid_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsp.bidrequestmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('min_bid', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dsp.categorymodel')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=True)),
                ('game_goal', models.CharField(max_length=20)),
                ('impressions_total', models.IntegerField(blank=True, null=True)),
                ('rounds_left', models.IntegerField(blank=True, null=True)),
                ('auction_type', models.IntegerField(choices=[(1, '1'), (2, '2')])),
                ('mode', models.CharField(choices=[('free', 'Free'), ('script', 'Script')], max_length=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impression_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('click_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('conversion_revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency_capping', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('win', models.BooleanField()),
                ('click', models.BooleanField(blank=True, null=True)),
                ('conversion', models.BooleanField(blank=True, null=True)),
                ('revenue', models.IntegerField(blank=True, null=True)),
                ('bid_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsp.bidrequestmodel')),
                ('bid_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsp.bidresponsemodel')),
            ],
        ),
        migrations.CreateModel(
            name='CreativeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(limit_choices_to={'config__current': True}, on_delete=django.db.models.deletion.CASCADE, to='dsp.campaignmodel')),
                ('categories', models.ManyToManyField(to='dsp.categorymodel')),
            ],
        ),
        migrations.AddField(
            model_name='campaignmodel',
            name='config',
            field=models.ForeignKey(limit_choices_to={'current': True}, on_delete=django.db.models.deletion.CASCADE, to='dsp.configmodel'),
        ),
        migrations.AddField(
            model_name='bidresponsemodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='bid_responses', to='dsp.categorymodel'),
        ),
        migrations.AddField(
            model_name='bidrequestmodel',
            name='blocked_categories',
            field=models.ManyToManyField(blank=True, related_name='blocked_bid_requests', to='dsp.categorymodel'),
        ),
        migrations.AddField(
            model_name='bidrequestmodel',
            name='config',
            field=models.ForeignKey(limit_choices_to={'current': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='dsp.configmodel'),
        ),
        migrations.CreateModel(
            name='UserImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('impressions', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsp.campaignmodel')),
            ],
            options={
                'unique_together': {('user_id', 'campaign')},
            },
        ),
    ]
